### ISSUE TITLE
Enable nginx annotations

### ISSUE THREAD

**Issue by Attoy** [Azure/aks-app-routing-operator#156]
Hello there,

We are still forced to use non-managed NGINX because we use some annotations like client-max-body-size and proxy-body-size. It would be nice to be able to use them with the Azure managed solution.

Thanks,
Leandro

**Comment by OliverMKing** [comment]
Hi @Attoy! Using annotations on the Ingress level to configure NGINX is supported today. 

We are adding support for global configurations through a CRD and can add these requests to the backlog. Just to confirm are you asking for global NGINX configuration?

Thanks!

**Comment by Attoy** [comment]
Hey @OliverMKing , thanks for your quick reply.

I meant the nginx.ingress.kubernetes.io/* annotations in the ingress manifest, however I see that you updated the documentation today and they are finally supported so please disregard my "issue" and mark it as resolved already!

Thanks!
