### ISSUE TITLE
Question about when v0.2.3 will be released

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/aks-app-routing-operator#244]
Previous issue: https://github.com/Azure/AKS/issues/4332

As of today, it looks like v0.2.3 is never being released. So I wonder when the new version will be released.
![image](https://github.com/Azure/aks-app-routing-operator/assets/142381267/31cb91b1-2d0b-458a-a50a-eb22f5cde1ca)

**Comment by OliverMKing** [comment]
It's released you just need to upgrade to Kubernetes version 1.30 (or higher) to use it. Addon release policies mean we release new features behind new preview K8s versions first.

**Comment by JoeyC-Dev** [comment]
AKS `1.30` is just being released 4 days ago (public preview). Not sure why the `v0.2.3` update announcement is announced in last month in AKS release notes, when the date is far before the actual `1.30` release date. 

Close the issue as being answered.
